templates:
  - name: "Bug report"
    about: "Report a bug in the repository"
    labels: ["bug"]
    assignees: []

  - name: "Feature request"
    about: "Request a new feature"
    labels: ["enhancement"]
    assignees: []
